const API_BASE = window.WCC_API_BASE || localStorage.getItem('WCC_API_BASE') || 'https://executive-engine-os.onrender.com';
const STORE_KEY = 'wcc_v1_1_batch2_threads';
const STATUSES = ['New','In Progress','Complete','Archived'];
const TEAM = ['Will','Emily','Sarah','Alex','James','Commander','Sir Homie'];
const CATEGORY_MAP = {
  Will:'Will', Emily:'Emily / Design', Sarah:'Sarah / Frontend', Alex:'Alex / Backend', James:'James / Testing', Commander:'Commander / Governance', 'Sir Homie':'Sir Homie / Strategy'
};
const DEFAULT_CATEGORY = 'Commander / Governance';
const $ = id => document.getElementById(id);
const nowISO = () => new Date().toISOString();
let state = { tasks: [], selectedId: null, view: 'home', query: '', health: null };

function escapeHtml(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function taskTitle(text=''){const clean=String(text).trim().replace(/\s+/g,' ');return clean.length>66?clean.slice(0,63)+'...':clean || 'Untitled task';}
function formatDate(s){try{return new Date(s).toLocaleString([], {month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});}catch{return '';}}
function toast(msg){$('toast').textContent=msg;$('toast').classList.remove('hidden');setTimeout(()=>$('toast').classList.add('hidden'),1600);}
function localSave(){localStorage.setItem(STORE_KEY, JSON.stringify(state.tasks));}
function localLoad(){try{return JSON.parse(localStorage.getItem(STORE_KEY)||'[]');}catch{return [];}}
async function api(path, opts={}){const res=await fetch(API_BASE+path,{headers:{'Content-Type':'application/json'},...opts});if(!res.ok)throw new Error(await res.text());return res.json();}
function normalizeTask(t){const ts=nowISO(); const status = t.status === 'Done' ? 'Complete' : (STATUSES.includes(t.status)?t.status:'New'); return {id:t.id||crypto.randomUUID(),title:t.title||taskTitle(t.message||''),category:t.category||DEFAULT_CATEGORY,sender:t.sender||'Will',destination:t.destination||t.category||DEFAULT_CATEGORY,message:t.message||t.title||'',status,comments:t.comments||[],files:t.files||[],participants:t.participants||[],activity:t.activity||[],test_entries:t.test_entries||[],created_at:t.created_at||ts,updated_at:t.updated_at||ts};}
function selected(){return state.tasks.find(t=>t.id===state.selectedId) || null;}
function activeTasks(){return state.tasks.filter(t=>!['Complete','Archived','Done'].includes(t.status)).sort((a,b)=>String(b.updated_at).localeCompare(String(a.updated_at)));}
function archivedTasks(){return state.tasks.filter(t=>['Complete','Archived','Done'].includes(t.status)).sort((a,b)=>String(b.updated_at).localeCompare(String(a.updated_at)));}
function addActivity(t,text){return {...t, activity:[...(t.activity||[]), {text, created_at:nowISO()}], updated_at:nowISO()};}
async function loadTasks(){try{const data=await api('/tasks');state.tasks=(data.tasks||[]).map(normalizeTask);localSave();}catch(e){state.tasks=localLoad().map(normalizeTask);} await loadHealth(); render();}
async function saveTask(task){const normalized=normalizeTask(task);try{const data=await api('/tasks',{method:'POST',body:JSON.stringify(normalized)});return normalizeTask(data.task);}catch(e){return normalized;}}
async function persistTask(task){const normalized=normalizeTask(task);try{const data=await api(`/tasks/${normalized.id}`,{method:'PUT',body:JSON.stringify(normalized)});return normalizeTask(data.task);}catch(e){return normalized;}}
async function updateSelected(patch, activityText){const t=selected(); if(!t) return; let next={...t,...patch,updated_at:nowISO()}; if(activityText) next=addActivity(next, activityText); const saved=await persistTask(next); state.tasks=state.tasks.map(x=>x.id===saved.id?saved:x); localSave(); render(activityText);}
async function loadHealth(){try{const h=await api('/health');state.health={api:true,...h, checked_at:nowISO()};}catch(e){state.health={api:false, error:'Backend health unavailable', checked_at:nowISO()};}}
function inferCategory(text){const lower=text.toLowerCase(); for(const name of TEAM){ if(lower.includes(name.toLowerCase())) return CATEGORY_MAP[name]; } return DEFAULT_CATEGORY;}
function fileRefFromInput(input,note='attached to task'){const f=input.files && input.files[0]; if(!f) return null; return {filename:f.name,type:f.type || f.name.split('.').pop() || 'file',note};}
function downloadText(filename, content){const blob=new Blob([content],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=filename;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),500);}
function selectedTaskForName(name){return state.tasks.find(t=>t.title===name)||state.tasks[0]||null;}

async function createQuickTask(){const input=$('quickTaskInput'); const text=input.value.trim(); const file=fileRefFromInput($('quickFileInput')); if(!text && !file){input.focus();return;} let task=normalizeTask({title:taskTitle(text || file.filename),message:text || file.filename,category:inferCategory(text),destination:inferCategory(text),status:'New',files:file?[file]:[],participants:[],activity:[{text:'task thread created',created_at:nowISO()}]}); if(file) task.activity.push({text:`file added: ${file.filename}`,created_at:nowISO()}); const saved=await saveTask(task); state.tasks=[saved,...state.tasks.filter(t=>t.id!==saved.id)]; state.selectedId=saved.id; state.view='thread'; localSave(); input.value=''; $('quickFileInput').value=''; render('Task created');}

function setNav(){document.querySelectorAll('.nav-item').forEach(b=>b.classList.remove('active')); const id=state.view==='search'?'searchBtn':state.view==='files'?'filesBtn':state.view==='archive'?'archiveBtnNav':'newTaskBtn'; $(id)?.classList.add('active'); $('searchResultsBlock').classList.toggle('hidden', state.view!=='search');}
function render(msg){setNav(); renderRecents(); renderCenter(); renderRight(); if(msg) toast(msg);}
function renderRecents(){const list=$('recentsList'); let rows=[]; if(state.view==='files'){ $('recentsHeading').textContent='Files'; const files=[]; state.tasks.forEach(t=>(t.files||[]).forEach(f=>files.push({task:t,...f}))); rows=files.slice(-20).reverse().map(f=>`<button class="recent-item" data-id="${f.task.id}"><span>${escapeHtml(f.filename)}</span><span class="pin">›</span><small>${escapeHtml(f.task.title)} · ${escapeHtml(f.note||'file')}</small></button>`); }
else if(state.view==='archive'){ $('recentsHeading').textContent='Archive'; rows=archivedTasks().map(t=>recentRow(t)); }
else { $('recentsHeading').textContent='Recents'; rows=state.tasks.slice().sort((a,b)=>String(b.updated_at).localeCompare(String(a.updated_at))).slice(0,8).map(t=>recentRow(t)); }
list.innerHTML=rows.join('') || '<p class="empty">No items yet.</p>'; renderSearch();}
function recentRow(t){return `<button class="recent-item ${t.id===state.selectedId?'active':''}" data-id="${t.id}"><span>${escapeHtml(t.title)}</span><span class="pin">⌁</span><small>${escapeHtml(t.category)} · ${escapeHtml(t.status)} · ${formatDate(t.updated_at)}</small></button>`;}
function renderSearch(){const box=$('searchInput'); if(state.view!=='search') return; const q=(state.query||'').toLowerCase().trim(); if(box && box.value !== state.query) box.value=state.query; if(!q){$('searchResultsList').innerHTML='<p class="empty">Type to search tasks, comments, and files.</p>';return;} const results=state.tasks.filter(t=>[t.title,t.message,t.category,t.status,...(t.comments||[]).map(c=>c.text),...(t.files||[]).map(f=>f.filename+' '+(f.note||''))].join(' ').toLowerCase().includes(q)); $('searchResultsList').innerHTML=results.map(t=>`<button class="search-row" data-id="${t.id}"><span>${escapeHtml(t.title)}</span><span>›</span><small>${escapeHtml(t.category)} · ${escapeHtml(t.status)}</small></button>`).join('') || '<p class="empty">No search results.</p>';}
function taskRow(t){const count=(t.comments||[]).length; return `<li class="task-card ${t.id===state.selectedId?'active':''}" data-id="${t.id}"><strong>${escapeHtml(t.title)}</strong><div class="task-meta"><span>${escapeHtml(t.category)}</span><span class="status-badge">${escapeHtml(t.status)}</span><span>${count} comments</span><span>${formatDate(t.updated_at)}</span></div></li>`;}
function renderCenter(){const t=selected(); if(state.view==='thread' && t) return renderThread(t); const heading=$('taskListHeading'); let items=[]; if(state.view==='archive'){heading.textContent='Archive'; items=archivedTasks();}
else if(state.view==='all'){heading.textContent='All Task Threads'; items=state.tasks.slice().sort((a,b)=>String(b.updated_at).localeCompare(String(a.updated_at)));}
else if(state.view==='files'){heading.textContent='Files'; return renderFilesCenter();}
else {heading.textContent='Today’s Tasks'; items=activeTasks();}
const older=items.filter(t=>new Date(t.created_at).toDateString()!==new Date().toDateString()); const today=items.filter(t=>new Date(t.created_at).toDateString()===new Date().toDateString()); let html=(today.length?today:items).map(taskRow).join(''); if(state.view==='home' && older.length){html += `<h2 class="older-title">10 Tasks that that are a few days old ...</h2>`+older.map(taskRow).join('');} $('centerTaskList').innerHTML=html || '<li class="empty">No active task threads yet.</li>';}
function renderFilesCenter(){const files=[]; state.tasks.forEach(t=>(t.files||[]).forEach(f=>files.push({task:t,...f}))); $('centerTaskList').innerHTML=files.slice().reverse().map(f=>`<li class="task-card" data-id="${f.task.id}"><strong>${escapeHtml(f.filename)}</strong><div class="task-meta"><span>${escapeHtml(f.task.title)}</span><span>${escapeHtml(f.note||'file')}</span><span>${escapeHtml(f.type||'file')}</span></div></li>`).join('') || '<li class="empty">No files yet.</li>';}
function renderThread(t){$('taskListHeading').textContent='Task Thread'; const comments=(t.comments||[]).map((c,i)=>`<div class="comment-item"><div class="comment-text" contenteditable="true" data-comment-index="${i}">${escapeHtml(c.text)}</div><small>${escapeHtml(c.author||'Will')} · ${formatDate(c.created_at)}</small></div>`).join(''); const files=(t.files||[]).map(f=>`<li>- ${escapeHtml(f.filename)} ${f.note?'('+escapeHtml(f.note)+')':''}</li>`).join(''); $('centerTaskList').innerHTML=`<li class="thread-card"><div class="thread-header"><div><div id="threadTitle" class="thread-title" contenteditable="true">${escapeHtml(t.title)}</div><select id="threadCategory" class="category-select">${Object.values(CATEGORY_MAP).map(c=>`<option ${c===t.category?'selected':''}>${escapeHtml(c)}</option>`).join('')}</select><div class="task-meta"><span class="status-badge">${escapeHtml(t.status)}</span><span>${formatDate(t.updated_at)}</span></div></div><div class="thread-actions"><button id="progressBtn" class="secondary" type="button">In Progress</button><button id="completeBtn" type="button">Complete</button></div></div><div class="original-message" id="threadMessage" contenteditable="true"><strong>Original Message</strong>${escapeHtml(t.message||'')}</div><div class="comments-title">Comments / Replies</div><div class="comments-list">${comments||'<p class="empty">No comments yet.</p>'}</div><form id="commentForm" class="comment-form"><input id="commentInput" class="comment-input" type="text" placeholder="Add another comment / reply..." autocomplete="off" /><label class="file-inline-label">+ file<input id="commentFileInput" class="comment-file" type="file" /></label><button type="submit">Add</button></form><div class="comments-title">Files</div><ul>${files||'<li class="empty">No files attached.</li>'}</ul></li>`; bindThread();}
function bindThread(){const t=selected(); if(!t) return; $('threadTitle').onblur=()=>{const v=$('threadTitle').innerText.trim(); if(v && v!==t.title) updateSelected({title:v},'task name updated');}; $('threadMessage').onblur=()=>{const raw=$('threadMessage').innerText.replace(/^Original Message\s*/,'').trim(); if(raw!==t.message) updateSelected({message:raw},'original message updated');}; $('threadCategory').onchange=e=>updateSelected({category:e.target.value,destination:e.target.value},'category updated'); document.querySelectorAll('[data-comment-index]').forEach(el=>el.onblur=()=>{const i=Number(el.dataset.commentIndex); const comments=[...(selected()?.comments||[])]; const text=el.innerText.trim(); if(comments[i] && comments[i].text!==text){comments[i]={...comments[i],text}; updateSelected({comments},'comment updated');}}); $('commentForm').onsubmit=async e=>{e.preventDefault(); const current=selected(); const input=$('commentInput'); const text=input.value.trim(); const file=fileRefFromInput($('commentFileInput'),'attached to comment'); if(!text && !file){input.focus();return;} const comments=[...(current.comments||[])]; if(text) comments.push({text,author:'Will',created_at:nowISO()}); const files=[...(current.files||[])]; if(file) files.push(file); await updateSelected({comments,files}, file?`comment/file added: ${file.filename}`:'comment added');}; $('progressBtn').onclick=()=>updateSelected({status:'In Progress'},'status changed to In Progress'); $('completeBtn').onclick=()=>{if(confirm('Are you sure you want to complete this task?')) updateSelected({status:'Complete'},'task completed and archived').then(()=>{state.selectedId=null;state.view='home';render();});};}
function renderRight(){const t=selected(); const globalActivity=state.tasks.flatMap(x=>(x.activity||[]).map(a=>({...a,task:x.title}))).sort((a,b)=>String(b.created_at).localeCompare(String(a.created_at))); $('activityList').innerHTML=(t?(t.activity||[]):globalActivity).slice(-8).reverse().map(a=>`<li>- ${escapeHtml(a.text)}${a.task?` · ${escapeHtml(a.task)}`:''}</li>`).join('') || '<li>- No activity yet</li>'; const files=[]; state.tasks.forEach(x=>(x.files||[]).forEach(f=>files.push({...f,task:x.title,updated_at:x.updated_at}))); $('latestFilesList').innerHTML=files.slice(-6).reverse().map(f=>`<li data-id="${escapeHtml((state.tasks.find(x=>x.title===f.task)||{}).id||'')}">- ${escapeHtml(f.filename)} · ${escapeHtml(f.task)}</li>`).join('') || '<li>- No files yet</li>'; $('taskFilesList').innerHTML=(t?.files||[]).map(f=>`<li data-id="${escapeHtml(t.id)}">- ${escapeHtml(f.filename)}${f.note?' ('+escapeHtml(f.note)+')':''}</li>`).join('') || '<li>- Select a task to view files</li>'; const h=state.health; $('systemHealthList').innerHTML=`<li>/health - <span class="${h?.api?'health-good':'health-warn'}">${h?.api?'GOOD':'CHECK'}</span></li><li>Backend Status - ${h?.api?'Connected':'Unavailable'}</li><li>Database Status - ${h?.supabase_configured?'Supabase configured':'Local fallback / not configured'}</li><li>Supabase Status - ${h?.supabase_configured?'Configured':'Not configured'}</li><li>Last Check - ${formatDate(h?.checked_at)}</li>`; $('testList').innerHTML=(t?.test_entries||[]).map(x=>`<li>${escapeHtml(x.label)} - ${escapeHtml(x.status||'GOOD')} ${x.note?'· '+escapeHtml(x.note):''}</li>`).join('') || '<li>health - GOOD</li><li>response - GOOD</li><li>test - GOOD</li>'; $('participantsList').innerHTML=(t?.participants||[]).map(p=>`<li>- ${escapeHtml(p.name)}</li>`).join('') || '<li>- Select task participants</li>'; $('participantControls').classList.toggle('hidden', !t);}
function seedSelects(){ $('participantSelect').innerHTML=TEAM.map(n=>`<option>${escapeHtml(n)}</option>`).join('');}
function openThreadFromEvent(e){const row=e.target.closest('[data-id]'); if(row){state.selectedId=row.dataset.id;state.view='thread';render();}}
$('homeLogo').onclick=()=>{state.selectedId=null;state.view='home';state.query='';render();};
$('newTaskBtn').onclick=()=>{$('quickTaskInput').focus();state.view='home';state.selectedId=null;render();};
$('quickPlus').onclick=()=>{$('quickTaskInput').focus();};
$('quickTaskForm').onsubmit=e=>{e.preventDefault();createQuickTask();};
$('searchBtn').onclick=()=>{state.selectedId=null;state.view='search';state.query='';render();setTimeout(()=>$('searchInput').focus(),0);};
$('searchInput').oninput=e=>{state.query=e.target.value;renderSearch();};
$('searchInput').onkeydown=e=>{if(e.key==='Escape'){state.view='home';state.query='';render();}};
$('filesBtn').onclick=()=>{state.selectedId=null;state.view='files';render();};
$('archiveBtnNav').onclick=()=>{state.selectedId=null;state.view='archive';render();};
$('viewAllBtn').onclick=()=>{state.selectedId=null;state.view='all';render();};
$('recentsList').onclick=openThreadFromEvent;$('searchResultsList').onclick=openThreadFromEvent;$('centerTaskList').onclick=openThreadFromEvent;
document.querySelectorAll('.doc-card').forEach(card=>card.addEventListener('click',()=>{const name=card.dataset.doc||'WCC document';downloadText(name.replace(/\s+/g,'_')+'.json',JSON.stringify({document:name,exported_at:nowISO(),tasks:state.tasks},null,2));toast('Document export ready');}));
document.querySelectorAll('.tiny-action').forEach((b,i)=>b.onclick=()=>{if(i===0){downloadText('wcc-export.json',JSON.stringify({exported_at:nowISO(),tasks:state.tasks},null,2));toast('WCC export ready');}else{state.view='all';state.selectedId=null;render('Showing all task threads');}});
$('refreshHealthBtn').onclick=async()=>{await loadHealth();render('System health refreshed');};
$('testEntryForm').onsubmit=e=>{e.preventDefault();const t=selected();const input=$('testEntryInput');const note=input.value.trim();if(!t){toast('Select a task first');return;}if(!note){input.focus();return;}const entries=[...(t.test_entries||[]),{label:'QA note',note,status:'GOOD',created_at:nowISO()}];input.value='';updateSelected({test_entries:entries},'test environment updated');};
$('latestFilesList').onclick=openThreadFromEvent;$('taskFilesList').onclick=openThreadFromEvent;
$('addParticipantInline').onclick=()=>{const t=selected(); if(!t) return; const name=$('participantSelect').value; const existing=t.participants||[]; if(existing.some(p=>p.name===name)) return; updateSelected({participants:[...existing,{name,role:CATEGORY_MAP[name]||''}]},`participant added: ${name}`);};
seedSelects(); loadTasks();
